--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sincos/Pictures/Wallpaper/anime/main3.jpg"

-- Special
background="#0F122D"
foreground="#c3c3ca"
cursor="#c3c3ca"

-- Colors
color0="#0F122D"
color1="#2d324e"
color2="#393755"
color3="#6f4a57"
color4="#492373"
color5="#392f84"
color6="#3f3b71"
color7="#94959e"
color8="#616277"
color9="#3C4368"
color10="#4D4A72"
color11="#956375"
color12="#622F9A"
color13="#4D3FB1"
color14="#554F97"
color15="#c3c3ca"
