# Shell variables
# Generated by 'wal'
wallpaper="/home/sincos/Pictures/Wallpaper/anime/main3.jpg"

# Special
background='#0F122D'
foreground='#c3c3ca'
cursor='#c3c3ca'

# Colors
color0='#0F122D'
color1='#2d324e'
color2='#393755'
color3='#6f4a57'
color4='#492373'
color5='#392f84'
color6='#3f3b71'
color7='#94959e'
color8='#616277'
color9='#3C4368'
color10='#4D4A72'
color11='#956375'
color12='#622F9A'
color13='#4D3FB1'
color14='#554F97'
color15='#c3c3ca'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
